// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXmBPHt3vVeZvx84S-i7MERkF7Rt5VVkQ',
    appId: '1:306853215674:android:9624a2a8ce4fef15acf183',
    messagingSenderId: '306853215674',
    projectId: 'foxyads-66291',
    storageBucket: 'foxyads-66291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBND2QSubER02khr0bPqD7qWh9glbcTBjQ',
    appId: '1:306853215674:ios:cfcde086c3692f64acf183',
    messagingSenderId: '306853215674',
    projectId: 'foxyads-66291',
    storageBucket: 'foxyads-66291.firebasestorage.app',
    androidClientId: '306853215674-uip24eu2fjoqndsrgdtcc2r8ago6rk1c.apps.googleusercontent.com',
    iosClientId: '306853215674-fuu2isjh94cll9s7m8udngsivn3e784t.apps.googleusercontent.com',
    iosBundleId: 'com.wildfoxy.foxyAds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe9ucPtlUIK6ANitNXbyc8b2h95GyTKsw',
    appId: '1:306853215674:web:4968c188bff7b515acf183',
    messagingSenderId: '306853215674',
    projectId: 'foxyads-66291',
    authDomain: 'foxyads-66291.firebaseapp.com',
    storageBucket: 'foxyads-66291.firebasestorage.app',
    measurementId: 'G-CLV8125XNL',
  );
}
